function imprimirNoConsole() {
    console.log("Olá, Mundo!");
}   console.log("O numero é: " + num);
}

imprimirUmNumero(2);
imprimirUmNumero(4);
imprimirUmNumero(6);
imprimirUmNumero(8);

const numeroAleatorio = function() {
    console.log(Math.random());
}

numeroAleatorio();
numeroAleatorio();

const numerosPares = function() {
    console.log(Math.random());
}

numerosPares();
numerosPares();

imprimirNoConsole();

function imprimirUmNumero(num) {
  